apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knowledge-assistant-ingress

spec:
  ingressClassName: nginx

  rules:
    - host: auto-eng.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 8501